def get_video():
    return "BAACAgQAAxkDAAIDFmkFRzW2KMEZHjRSofbLahC-6XbvAAJBHAACYgABKVBYG-keM4qsfDYE"

def get_voices():
    return (
        "CQACAgQAAxkDAAIDF2kFR6XX4iVTRSfsNUzpK7KiOuSFAAJCHAACYgABKVDihVOfnj4vZjYE",
        "CQACAgQAAxkDAAIDGGkFR6aS4GoWNCV8Uk8aOU3cLxWlAAJDHAACYgABKVDktWW4fhdm8TYE",
        "CQACAgQAAxkDAAIDGWkFR6hmqo4Kmi_ClGWrZiYoPMyAAAJEHAACYgABKVAAAV0Y9GbVbxI2BA",
        "CQACAgQAAxkDAAIDGmkFR6oK0BPY-L3ttKiGGgV_XHCPAAJFHAACYgABKVBVGseybGXNnzYE",
        "CQACAgQAAxkDAAIDG2kFR6ztCtdB8-6qxnCRZe8-VDSxAAJGHAACYgABKVAR_h-WOYfkNTYE",
        "CQACAgQAAxkDAAIDHGkFR66UfgUcFRsOCSarJio9ITXoAAJHHAACYgABKVBL7kZy-XK7EjYE",
    )

