def get_script_audios():
    return {
    "Default":                        {"greeting": 'AwACAgQAAxkDAAKAv2nn-HYxnIrMXbxsAh2W7QIFv88OAAJbIQACp3JBU_bml_LMbnQ3OwQ', "goodbye": 'AwACAgQAAxkDAAKAvmnn-HRplA7ZEONpwAq-rCZ2E4bSAAJaIQACp3JBU2_hjDVHcjJcOwQ'},
    "Bank Security":                  {"greeting": 'AwACAgQAAxkDAAKAwWnn-N25NzrUzv-lHJfUKo8D7u4GAAJeIQACp3JBU0PGcPAwGeZGOwQ', "goodbye": 'AwACAgQAAxkDAAKAwGnn-NiGsEvrY_yxdBZVRLMwVK9DAAJdIQACp3JBU-sMiFtr8ssaOwQ'},
    "Delivery":                       {"greeting": 'AwACAgQAAxkDAAKAw2nn-WgbXgeVayE1u5S3hVe0GZn8AAJhIQACp3JBUxNQIb_U9zX4OwQ', "goodbye": 'AwACAgQAAxkDAAKAwmnn-WcYw7kx45N3GUUiU5Ie3QrvAAJgIQACp3JBUwi8_TPbOvckOwQ'},
    "Amazon":                         {"greeting": 'AwACAgQAAxkDAAKAxWnn-iVCfAZF1-_OKR7yjwQvw23qAAJjIQACp3JBU2a3JWZ3kYIeOwQ', "goodbye": 'AwACAgQAAxkDAAKAxGnn-iTKGAtYKyhuA4XkM-I48WItAAJiIQACp3JBUzM4jqvB0DCPOwQ'},
    "PayPal":                         {"greeting": 'AwACAgQAAxkDAAKAx2nn-o2Oi1kMAoacsYnF-hcDKr27AAJlIQACp3JBUzGPmep2iUYeOwQ', "goodbye": 'AwACAgQAAxkDAAKAxmnn-oxL0aITfJBAq1Gp9LZj66zKAAJkIQACp3JBU7TRewfiwGoAATsE'},
    "Crypto Exchange":                {"greeting": 'AwACAgQAAxkDAAKAyWnn-vQIKNX5L6UsO1fdZKdkWrBJAAJnIQACp3JBUxO2blZawPd6OwQ', "goodbye": 'AwACAgQAAxkDAAKAyGnn-vMhE2qf1p1qfwb3HKoJe0O6AAJmIQACp3JBU_aOyw3wKcjQOwQ'},
    "Insurance":                      {"greeting": 'AwACAgQAAxkDAAKAy2nn-0lIrMRByo1MO9eJdKPJkqkYAAJpIQACp3JBU7_VhB8MwixcOwQ', "goodbye": 'AwACAgQAAxkDAAKAymnn-0jGR64jaM6bMOHEA78m8htmAAJoIQACp3JBU9BJftdPL2dsOwQ'},
    "Telecom":                        {"greeting": 'AwACAgQAAxkDAAKAzWnn-46N95ubrozhUxKbsYKjTJiSAAJrIQACp3JBU-IGL9NkSsE1OwQ', "goodbye": 'AwACAgQAAxkDAAKAzGnn-41h02_je8gvcgqfEcgKljvLAAJqIQACp3JBUxS6BcQnf70kOwQ'},
    "Email Security":                 {"greeting": 'AwACAgQAAxkDAAKAz2nn_Dr5WurbCy2OkzjE5zjVc1X2AAJtIQACp3JBUwgCsSAxUBLVOwQ', "goodbye": 'AwACAgQAAxkDAAKAzmnn_Dm1Nw0x06HM1HOfEH_Xb90dAAJsIQACp3JBU9Cs-6LwwNcpOwQ'},
    "Tax Authority":                  {"greeting": 'AwACAgQAAxkDAAKA0Wnn_KVSOcTvMMQTZYUZOiZ-i7dFAAJvIQACp3JBUzxc36ccWM2IOwQ', "goodbye": 'AwACAgQAAxkDAAKA0Gnn_KTxDH-X0bxPRHitzpW314O-AAJuIQACp3JBU_wyKOqWGidiOwQ'},
    "Marcus - Unauthorized Transfer": {"greeting": 'AwACAgQAAxkDAAKA1Gnn_OU-fp70XJNYKxoTHrMq9SB_AAJxIQACp3JBU9BT5MT-vmq5OwQ', "goodbye": 'AwACAgQAAxkDAAKA02nn_OS8oeKnpwst0pO6Yr_4sVmFAAJwIQACp3JBU0ciSDBDv-UCOwQ'},
    "Marcus - Login Alert":           {"greeting": 'AwACAgQAAxkDAAKA1mnn_Vyk-kaIU7VlwbuDbbctckMMAAJzIQACp3JBU-WctNWsIVZ6OwQ', "goodbye": 'AwACAgQAAxkDAAKA1Wnn_VsfZTlNaD0EpdpQ9wd-W1FBAAJyIQACp3JBU9hMHPROxr6eOwQ'},
    "Marcus - CD Withdrawal":         {"greeting": 'AwACAgQAAxkDAAKA2Gnn_ZwJ7oAmFvnmhOqj5D6hPQcYAAJ1IQACp3JBUxa17zSsVi_NOwQ', "goodbye": 'AwACAgQAAxkDAAKA12nn_ZvEhG-oXcjctrcBWUkhP5fxAAJ0IQACp3JBU0rX9VLZHcyUOwQ'},
    "Marcus - Personal Loan":         {"greeting": 'AwACAgQAAxkDAAKA2mnn_eQfmP_8sKKHREzBnT6ZhlOAAAJ3IQACp3JBU7euNSfVsdfeOwQ', "goodbye": 'AwACAgQAAxkDAAKA2Wnn_eMdacNmXsU5xFcqm1SJzh8sAAJ2IQACp3JBU1wkVu-zkXtfOwQ'},
    "Barclays - Fraud Alert":         {"greeting": '', "goodbye": ''},
    "Barclays - Login Alert":         {"greeting": '', "goodbye": ''},
    "Barclays - Wire Transfer":       {"greeting": '', "goodbye": ''},
    "Truist - Fraud Alert":           {"greeting": '', "goodbye": ''},
    "Truist - Account Access":        {"greeting": '', "goodbye": ''},
    "Truist - Zelle Transfer":        {"greeting": '', "goodbye": ''},
    "ID.me - Identity Verification":  {"greeting": '', "goodbye": ''},
    "ID.me - Suspicious Login":       {"greeting": '', "goodbye": ''},
    "ID.me - Benefits Verification":  {"greeting": '', "goodbye": ''},
    "Apple":                          {"greeting": '', "goodbye": ''},
    "Google":                         {"greeting": '', "goodbye": ''},
    "Microsoft":                      {"greeting": '', "goodbye": ''},
    "Chase Bank":                     {"greeting": '', "goodbye": ''},
    "Wells Fargo":                    {"greeting": '', "goodbye": ''},
    "Bank of America":                {"greeting": '', "goodbye": ''},
    "Venmo":                          {"greeting": '', "goodbye": ''},
    "Cash App":                       {"greeting": '', "goodbye": ''},
    "Zelle":                          {"greeting": '', "goodbye": ''},
    "ID.ME - Login Alert":            {"greeting": '', "goodbye": ''},
}
